bodyweight = 70.0
units = "metric"
prompt_for_bodyweight = true
streak_interval_days = 1

[theme]
header_color = "Green"

[pb_notifications]
enabled = true
notify_weight = false
notify_reps = true
notify_duration = true
notify_distance = false
